### ISSUE TITLE
Update banner text with accurate .gov/TLS text

### ISSUE THREAD

**Issue by konklone** [18F/web-design-standards-docs#315]
In https://github.com/18F/web-design-standards/issues/1738, we discussed and addressed inaccurate text in the banner about TLS and .gov domains. https://www.usa.gov now has accurate text, but the USWDS site itself does not:

<img width="1060" alt="screen shot 2017-06-09 at 1 33 58 pm" src="https://user-images.githubusercontent.com/4592/26987114-4d970036-4d18-11e7-9db0-77862151c2e2.png">

**Comment by AndreaSigz** [comment]
Thanks @konklone. @donjo or @msecret any thoughts?

**Comment by konklone** [comment]
Any thoughts here? Users of USWDS are continuing to stand up new websites with inaccurate text that will reduce our credibility with the security community.

Another recent example is https://developers.login.gov. I just went and tried to figure out how I could update the text to track with usa.gov, and I can't figure out an easy way to do this -- it looks like usa.gov just fixed the text directly in their own infrastructure. 

Where in the USWDS ecosystem can we update this text so that it gets fixed downstream, and especially in new applications?

**Comment by donjo** [comment]
@konklone I think this got lost in the shuffle of team member transitions. I just added 18F/web-design-standards#1748 to the next sprint and assigned it to myself so I can look over all the feedback everyone gave and determine where to go next.

**Comment by konklone** [comment]
This isn't fixed - the USWDS docs site has the same inaccurate text at https://standards.usa.gov:

<img width="1136" alt="screen shot 2017-08-06 at 1 13 40 pm" src="https://user-images.githubusercontent.com/4592/29005407-157267e0-7aa9-11e7-82f7-9b68ab21d0cb.png">

(It's also got some display issues, as can be seen - this is from Chrome on OS X, maximized window on a Macbook Pro.)

**Comment by AndreaSigz** [comment]
@donjo @toolness

**Comment by rememberlenny** [comment]
@konklone cloud.gov wanted to update the top bar with this language. Can we move forward using the example on standards.usa.gov?

**Comment by msecret** [comment]
It looks like there's the correct banner on the components site: https://components.standards.usa.gov/components/detail/banner.html

@konklone can you confirm that's correct, and I can work on updating the main site with it.

**Comment by konklone** [comment]
Yep, `components.standards.usa.gov` has the right language, and I recommend the new language for `cloud.gov`.

To be clear, I'm actually pretty agnostic about whether to add new text to a site that doesn't have it. The difficult process of updating text across the USWDS ecosystem has made me a bit more skeptical about the viability of this sort of thing.

**Comment by rememberlenny** [comment]
This is awesome. I didnt know about this `components` application. Thanks @msecret and @konklone

**Comment by toolness** [comment]
Er, I think this is actually a duplicate of #374?  (Or rather, that issue was a duplicate of this one, since this one is oldest.)  In any case, it was fixed in #383, it's just not actually live yet, so I'm going to close this issue. Unless I'm totally mistaken, in which case feel free to re-open it!

@konklone do you think the text itself will change much as time goes on?  If so, we could potentially add the content dynamically via JS, which would give us the option to broadcast any changes out to all sites that use the USWDS, either when their maintainers manually update the Standards, or even dynamically via a cross-origin API of some sort.

**Comment by konklone** [comment]
> @konklone do you think the text itself will change much as time goes on? If so, we could potentially add the content dynamically via JS, which would give us the option to broadcast any changes out to all sites that use the USWDS, either when their maintainers manually update the Standards, or even dynamically via a cross-origin API of some sort.

It's a neat idea, but I think that would be an unreasonable privacy/security risk for the benefit that easy text distribution would give. (The hosted CDN would receive user agent and other information via HTTP, and a compromise of the hosted CDN would compromise the session of the site making use of it.)

**Comment by konklone** [comment]
The old text is still present here: https://standards.usa.gov/page-templates/landing/

**Comment by brittag** [comment]
I appreciate @konklone persisting on this - from my experience as a person who helps lead a product that uses components from the USWDS, the incorrect text on standards.usa.gov confused my team just a month ago. We ended up using the updated text because we're unusually familiar with the subject area, how USWDS works, and how to search issue trackers.

* On August 22, my cloud.gov team opened a card in our own issue tracker about pulling in the banner text from standards.usa.gov, because my team wanted to stay up to date with the USWDS.
* I saw this planned task and noticed that the banner text looked factually incorrect to me (specifically because I know `.fs.fed.us` is a legitimate government domain name and I'm familiar with the broad outlines of how HTTPS works), so I went into the issue tracker here and searched for anyone else noticing the same problem, and I sent the following links to my team to review before implementing the standards.usa.gov text: https://github.com/18F/web-design-standards/issues/1738#issuecomment-290561353 + https://github.com/18F/web-design-standards/issues/1748#issuecomment-288832017 + https://github.com/18F/web-design-standards-docs/issues/315#issuecomment-320519677
* You can see above in this thread that my cloud.gov teammate @rememberlenny reached out here to ask for confirmation about the right text to implement - the text on standards.usa.gov or the text at https://components.standards.usa.gov/components/detail/banner.html (https://github.com/18F/web-design-standards-docs/issues/315#issuecomment-325037680).

So we avoided adding the wrong text, but it's an example of how this depended on us doing extra research (and how it added confusion to our process).

**Comment by thisisdano** [comment]
And this component should also be updated in the USWDS Jekyll theme: 
https://github.com/18F/uswds-jekyll

**Comment by line47** [comment]
I've got a PR in for updating the USA banner for the https://github.com/18F/uswds-jekyll
If someone here wants to review 👍 

https://github.com/18F/uswds-jekyll/pull/43

**Comment by toolness** [comment]
Shoot, sorry about this folks!  The banner was fixed on our main development branch back on August 21, but we hadn't pushed it to production yet.  We just pushed a hotfix, though, so standards.usa.gov should be correct by the time you read this.

I think there's a number of reasons behind why this took so long to resolve, and it might be worth doing a brief retro on, so that the same kind of thing doesn't happen again once this project moves to OPP on October 1. Some things I can think of include:

* There isn't currently a very well-defined prioritization process for issues. I think @konklone is correct when he says that the long time it took to resolve this issue "means ... that the team isn't perceiving it as a significant issue".  Perhaps some sort of heuristic for deciding what's significant vs. what's not should be agreed upon.

* The amount of time/effort it took to find and change all occurrences of the gov banner across just the core USWDS and its documentation is emblematic of the core problem @konklone referred to, whereby just updating the govbanner content is non-trivial because it's static HTML. Within the USWDS at least, such schisms will be less frequent as the project moves towards more [reuse of Fractal components](https://github.com/18F/web-design-standards/pull/2050) over copy-paste of HTML snippets. Still, though, just the fact that it took us so long to update our own govbanner is indicative of the high maintenance cost of this particular kind of component.

* Currently, pushing changes to the documentation site is usually tightly coupled to releasing a new version of the Standards themselves. The latter is relatively high-risk compared to the former, yet the former is also very important (as this issue attests).  It may be useful to have a well-defined workflow for publishing important changes to the documentation that don't necessarily require re-publishing a new version of the core standards (in the case of the #397 hotfix, I just cherry-picked the relevant commit into the production branch, so maybe we should evaluate whether that kind of approach is a good idea in the long-term).

* The USWDS team has been juggling client work with core USWDS work, and because client work is what "pays the bills", core USWDS work can sometimes fall by the wayside. I guess this is a benefit of the Standards moving over to OPP.
