### ISSUE TITLE
[Repo]: License repo with resources we're using

### ISSUE THREAD

**Issue by maya** [18F/web-design-standards-docs#7]
## Description

Make sure our LICENSE is up to date with the resources we're using.

Will be based on https://github.com/18F/web-design-standards/blob/staging/LICENSE.md and added to README and CONTRIBUTING file.

**Comment by juliaelman** [comment]
@maya based [off of the work](https://github.com/18F/web-design-standards/pull/1455) that @kategarklavs and @jameshupp are doing around how the `LICENSE.md` appears in the `web-design-standards` repo, we are moving away from having the entire licensing file referenced in the `README.md` and `CONTRIBUTING.md`.

Since this repo is not for a distributed package, that includes several open source modules, I think our generic licensing file should suffice and we do not need to reference other than it being in the root level directory.

@jameshupp or @kategarklavs can either of you give me a 👍  or 👎  that this is correct?

**Comment by jameshupp** [comment]
That's correct. In addition to trying to keep those other files more readable, managing the licensing info in multiple places seemed to be leading to minor inconsistencies across the different `.md` files. It's more manageable in one place, and I think we can keep our references clear and direct enough. But happy to keep that language progressing if it's insufficient in the pull that @juliaelman just referenced.

**Comment by juliaelman** [comment]
@jameshupp thanks for your response! It's definitely more manageable to have in one place.

Going to close this issue, as there is no need to add the licensing information about these other packages since this is not a distributed code base.
